// Programming_Challenger.cpp : Defines the entry point for the console application.
//#include "LC_Display.h"
//#include "Interpreter.h"
//#include "Jolly_Jumper.h"
//#include "poker_hands.h"
//#include "hartals.h"
//#include "crypt_kicker.h"
//#include "stack_em_up.h"
//#include "yahtzee.h"
//#include "is_bigger_smarter.h"
//#include "distinct_sequence.h"
//#include "weights_and_measure.h"
//#include "Bicoloring.h"
#include "playing_the_wheels.h"

